config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects, only: [:index] do
    get 'options', on: :member
    get 'items', on: :member
  end
  resources :item_collects, only: [:index] do
    get 'add_promise', on: :member
    post 'save_promise', on: :member
  end

  namespace :api do
    namespace :v1 do
      get 'search', controller: 'people'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/builder/promise_form.rb
class Builder::PromiseForm
  include ActiveModel::Model
  attr_accessor :id, :name, :last_name, :ci, :phone, :amount, :item_collect_id
  validates :name, :amount, :item_collect_id, presence: true
  validate :unique_promise_by_person

  def unique_promise_by_person
    if self.id.present?
      person = Person.find self.id
      if person.promises.where(item_collect_id: self.item_collect_id).any?
        errors.add(:item_collect_id, 'anteriormente prometido!')
      end
    end
  end

  def save
    if valid?
      unless id.present?
        person = Person.find_or_create_by(name: name, last_name: last_name, ci: ci, phone: phone)
        @id = person.reload.id
      end
      person = Person.find id
      person.update(name: name, last_name: last_name, ci: ci, phone: phone)
      Promise.create(person_id: @id, item_collect_id: @item_collect_id,
                     amount: amount, current_state: 'pending')
      true
    else
      false
    end
  end
end

app/models/item_collect.rb
class ItemCollect < ApplicationRecord
  belongs_to :project

  has_many :promises, dependent: :destroy

  scope :pending, -> { where(current_state: 'pending') }

  before_save do
    if total_collect >= total_amount
      self.current_state = 'collected'
    end
  end

  after_create_commit do
    project.total_amount += total_amount
    project.save
  end

  def remaining_amount
    (self.total_amount - self.total_collect).abs
  end
end

app/models/person.rb
class Person < ApplicationRecord

  has_many :promises, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :custom_fields, against: [:name, :last_name, :ci, :phone], using: {
      tsearch: { prefix: true }
  }

  def full_name
    "#{name.try(:capitalize)} #{last_name.try(:capitalize)}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :item_collects, dependent: :destroy

  def receivables_amount
    amount = 0
    item_collects.each do |item_collect|
      item_collect.promises.receivables.each do |promise|
        amount += promise.amount
      end
    end
    amount
  end
end

app/models/promise.rb
class Promise < ApplicationRecord
  belongs_to :person
  belongs_to :item_collect

  scope :receivables, -> { where(current_state: 'pending') }

  before_save do
    if self.amount <= self.paid
      self.current_state = 'paid'
    end
  end

  after_save do
    if self.current_state == 'paid'
      item_collect.total_collect += self.paid
      item_collect.save
      project = item_collect.project
      project.total_collect += self.paid
      project.save
    end
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ApplicationController
  RESPONSE_SUCCESSFULLY = 'SUCCESSFULLY'
  RESPONSE_BAD = 'ERROR'
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < Api::V1::ApplicationController
  def search
    query = params[:query]
    return render json: {type: RESPONSE_SUCCESSFULLY, payload: []} unless query.present?
    people = Person.custom_fields(query)
    render json: {
        type: RESPONSE_SUCCESSFULLY,
        payload: ActiveModel::Serializer::CollectionSerializer.new(people, serializer: PersonSerializer)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/item_collects_controller.rb
class ItemCollectsController < ApplicationController
  before_action :set_item_collect
  def index; end

  def add_promise
    @promise_form = Builder::PromiseForm.new
    @promise_form.item_collect_id = @item_collect.id
  end

  def save_promise
    @promise_form = Builder::PromiseForm.new(promise_form_params)
    if @promise_form.save
      flash[:info] = 'Gracias por tus promesas, son de gran ayuda!'
      redirect_to items_project_path(@item_collect.project)
    else
      render 'add_promise'
    end
  end

  private
  def set_item_collect
    @item_collect = ItemCollect.find params[:id]
  end

  def promise_form_params
    params.require(:builder_promise_form).permit(:id, :name, :last_name, :ci, :phone, :amount, :item_collect_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:options, :items]

  def index
    @projects = Project.all.order(created_at: :desc)
  end

  def options; end

  def items
    @item_collects = @project.item_collects.order(total_amount: :desc)
    render 'item_collects/index'
  end

  private

  def set_project
    @project = Project.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def i18n_model_values(att_to_translate, instance_model)
    value_to_translate = instance_model.read_attribute att_to_translate
    value_to_translate = value_to_translate.to_s.underscore.split().join("_") if value_to_translate.present?
    model_to_translate = instance_model.class.to_s.try(:underscore)
    scope_to_translate = "model.#{model_to_translate}"
    I18n.t(value_to_translate, scope: scope_to_translate, default: instance_model.read_attribute(att_to_translate))
  end

end

app/helpers/item_collects_helper.rb
module ItemCollectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/item_collects/_row.html.erb
<tr>
  <td><%= index + 1 %></td>
  <td><%= item_collect.name %></td>
  <td><%= item_collect.description %></td>
  <td><%= number_to_currency(item_collect.unit_price) %></td>
  <td><%= item_collect.qty %></td>
  <td><%= number_to_currency(item_collect.total_amount) %></td>
  <td><%= number_to_currency(item_collect.total_collect) %></td>
  <td><%= number_to_currency(item_collect.promises.receivables.sum(:amount)) %></td>
  <td><%= i18n_model_values(:current_state, item_collect) %></td>
  <td class="text-center">
    <a href="<%= add_promise_item_collect_path(item_collect) %>" class="btn btn-info btn-sm active" role="button" aria-pressed="true">
      <i class="fas fa-edit"></i>
    </a>
  </td>
</tr>

app/views/item_collects/_table.html.erb
<table
  class="table table-bordered table-hover"
>
  <thead class="thead-light">
  <tr>
    <th>#</th>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Precio Unitario</th>
    <th>Cantidad</th>
    <th>Total requerido</th>
    <th>Total recolectado</th>
    <th>Pendiente de recolectar</th>
    <th>Estado</th>
    <th>Acciones</th>
  </tr>
  </thead>
  <tbody>
  <% item_collects.each_with_index do |item_collect, i| %>
    <%= render partial: 'item_collects/row', locals: {item_collect: item_collect, index: i} %>
  <% end %>
  </tbody>
</table>

app/views/item_collects/add_promise.html.erb
<div class="row mt-4">
  <div class="col">
    <%= form_for @promise_form, url: save_promise_item_collect_path(@item_collect) do |f| %>
      <%= render partial: 'layouts/errors', locals: {resource: @promise_form} %>
      <div class="shadow card">
        <div class="card-body">
          <h5 class="card-title">Datos Personales</h5>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', autocomplete: 'off', required: true %>
              <%= f.hidden_field :id, class: 'form-control'%>
              <%= f.hidden_field :item_collect_id, class: 'form-control'%>

              <small class="form-text text-muted">Buscar por nombre completo, ci o teléfono</small>
            </div>
            <div class="form-group col-md-6">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: 'form-control' %>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label :ci %>
              <%= f.text_field :ci, class: 'form-control' %>
            </div>
            <div class="form-group col-md-6">
              <%= f.label :phone %>
              <%= f.phone_field :phone, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
      <div class="shadow card mt-3">
        <div class="card-body">
          <h5 class="card-title">Promesa para <%= @item_collect.name %></h5>
          <div class="form-row">
            <div class="form-group col-md-6">
              <%= f.label :amount %>
              <%= f.number_field :amount, required: true %>
              <small class="form-text text-muted">
                Se necesita <%= number_to_currency @item_collect.remaining_amount %>
              </small>
            </div>
          </div>
        </div>
      </div>

      <div class="mt-2">
        <a href="<%= items_project_path(@item_collect.project) %>" class="btn btn-warning  active" role="button" aria-pressed="true">
          Volver
        </a>
        <button type="submit" class="btn btn-primary">Guardar</button>
      </div>
    <% end %>
  </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= javascript_pack_tag 'person/autocomplete' %>
<% end %>

app/views/item_collects/index.html.erb
<div class="row mt-4">
  <div class="col">
    <div class="row mt-4">
      <div class="col">
        <div class="card">
          <div class="card-header bg-secondary text-white">
            Items a recolectar para <%= @project.name %>
            <div class="float-right">
              <%= link_to 'Volver', projects_path, class: 'btn btn-warning' %>
            </div>
          </div>
          <div class="card-body">
            <%= render partial: 'item_collects/table', locals: {item_collects: @item_collects} %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-12">
    <% flash.each do |key, value| %>
      <% if %w(danger info primary default alert notice error).include?(key.to_s) %>
        <div class="alert alert-primary">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recaudación</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield :custom_css %>
</head>
<body class="bg-light">
<div class="container mt-4">
  <%= render partial: 'layouts/messages' %>
  <%= yield %>
</div>
<div class="remote-modals"></div>
<%= yield :scripts %>
</body>
</html>

app/views/projects/_row.html.erb
<tr>
  <td><%= project.name %></td>
  <td><%= project.description %></td>
  <td><%= number_to_currency(project.total_collect) %></td>
  <td><%= number_to_currency(project.total_amount) %></td>
  <td><%= number_to_currency(project.receivables_amount) %></td>
  <td><%= i18n_model_values(:active, project) %></td>
  <td class="text-center">
    <a href="<%= options_project_path(project) %>" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">
      <i class="fas fa-info"></i>
    </a>
  </td>
</tr>

app/views/projects/_table.html.erb
<table
  class="table table-bordered"
>
  <thead class="thead-light">
  <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Total Recaudado</th>
    <th>Monto a Recaudar</th>
    <th>Monto por Cobrar</th>
    <th>Estado</th>
    <th>Acciones</th>
  </tr>
  </thead>
  <tbody>
  <% projects.each do |project| %>
    <%= render partial: 'row', locals: {project: project} %>
  <% end %>
  </tbody>
</table>

app/views/projects/index.html.erb
<div class="row">
  <div class="col">
    <%= render partial: 'table', locals: {projects: @projects} %>
  </div>
</div>

app/views/projects/options.html.erb
<div class="row p-4">
  <a href="<%= items_project_path(@project) %>" class="shadow col col-4 offset-2 border border-primary mr-2 rounded text-center font-weight-bold">
    <%= image_pack_tag 'cobranza.svg', class: 'img-fluid' %>
    Promesas Pendientes de Entregar
  </a>
  <a href="<%= items_project_path(@project) %>" class="shadow col col-4 border border-primary rounded text-center font-weight-bold">
    <%= image_pack_tag 'promesa.png', class: 'img-fluid' %>
    Registrar Promesas
  </a>
</div>